### ISSUE TITLE
Cannot activate the 'Auto Hide KB' extension because it depends on the 'Command Task' extension, which is not loaded.

### ISSUE THREAD

**Issue by HighPriest** [kvoon3/vscode-command-task#1]
[Auto Hide KB](https://github.com/kvoon3/vscode-autohide-kb) repository has disabled Issues reporting, so I am writing here for awareness.

When I open a remote session inside VSCode, Auto Hide KB doesn't start & a notification `Cannot activate the 'Auto Hide KB' extension because it depends on the 'Command Task' extension, which is not loaded. Would you like to reload the window to load the extension?` pops up.

Installing & enabling your Command Task extension for the remote session, doesn't help.

P.S. Great work on these extensions. They work great outside of this minor inconvenience <3

**Comment by kvoon3** [comment]
Thanks for using this extension! Due to the fact that VS Code extensions are categorized into UI and workspace types, using Remote SSH or Remote Server may lead to issues with the activation order of extensions, which can disrupt their dependencies.

I have now kept the extensionKind of the two extensions consistent, it seems to be working fine，and you can also configure the `extensionKind` order of any VS Code extensions yourself:

```jsonc
// settings.json
"remote.extensionKind": {
  "kvoon.command-task": [
    "ui",
    "workspace"
  ],
  "kevin-kwong.vscode-autohide-keyboard": [
    "ui",
    "workspace"
  ]
}
```
